### ISSUE TITLE
Choosing a color doesn't fire a change event

### ISSUE THREAD

**Issue by zachschultz** [boonep/jquery-hex-colorpicker#2]
I am trying to watch for changes to the input I have the color picker on but for some reason selecting a color doesn't trigger a change event. Is there anything I am supposed to configure for this functionality?

**Comment by zachschultz** [comment]
Just looked through the source code and saw that you can adjust the submit callback like so:

```
    $(jQuery).hexColorPicker({
         'submitCallback': function() {
              this.elem.trigger('change');
          }
    });
```

**Comment by boonep** [comment]
Sorry for the delay.  Glad you figured it out!  I'll update the documentation.
